[tools]
age = "latest"
java = "corretto-24.0.2.12.1"
sops = "latest"

[env]
_.file = ".env.json"
SOPS_AGE_PUBLIC_KEY = "age10juh5a3dwefjsa48r0fmfmkgvvvtu0275ulyxg86ze2jy622945qs4ezjf"
SOPS_AGE_RECIPIENTS = "age10juh5a3dwefjsa48r0fmfmkgvvvtu0275ulyxg86ze2jy622945qs4ezjf"
